import React, { useState } from 'react';
import { LogoIcon, SearchIcon } from './icons';

interface WelcomeScreenProps {
  onSearch: (query: string) => void;
}

const suggestionsList = ["The Roman Empire", "Quantum Computing", "History of the Internet", "Photosynthesis"];

export const WelcomeScreen: React.FC<WelcomeScreenProps> = ({ onSearch }) => {
  const [query, setQuery] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (query.trim()) {
      onSearch(query.trim());
      setQuery('');
    }
  };

  return (
    <div className="text-center p-8 w-full max-w-3xl mx-auto flex flex-col items-center animate-fade-in pt-20">
      <LogoIcon className="w-24 h-24 mx-auto text-cyan-500 mb-6" />
      <h2 className="text-5xl font-bold text-white mb-3 tracking-tight">
        Infinite Wiki
      </h2>
      <p className="text-xl text-gray-400 mb-8">
        An endless web of knowledge, generated by AI. Start with any topic.
      </p>
      
      <form onSubmit={handleSubmit} className="w-full max-w-xl mb-6">
        <div className="relative">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Explore a topic..."
            className="w-full bg-gray-800 border border-gray-600 rounded-full text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500/50 hover:border-cyan-500/50 transition duration-200 py-3 text-lg pl-12 pr-6"
          />
          <div className="absolute inset-y-0 left-0 flex items-center pointer-events-none pl-4">
            <SearchIcon className="h-6 w-6 text-gray-400" />
          </div>
        </div>
      </form>
      
      <div className="flex flex-wrap justify-center items-center gap-3 text-sm">
        <span className="text-gray-400">Try:</span>
        {suggestionsList.map(s => (
          <button 
            key={s}
            type="button"
            onClick={() => onSearch(s)}
            className="bg-gray-800 hover:bg-gray-700 text-gray-300 px-4 py-2 rounded-full transition-colors duration-200"
          >
            {s}
          </button>
        ))}
      </div>
    </div>
  );
};
